name: instagram_clone
description: Instagram clone application made with Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # firebase
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_storage: ^8.0.0
  cloud_firestore: ^1.0.0
  google_sign_in: ^4.5.9

  # flutter
  flutter_redux: ^0.7.0
  image_picker: ^0.7.2
  location: ^4.1.1

  # dart
  redux: ^4.0.0+3
  redux_epics: ^0.14.0
  built_value: ^8.0.0
  built_collection: ^5.0.0
  freezed_annotation: ^0.12.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  built_value_generator: any
  freezed: any

dependency_overrides:
  rxdart: ^0.25.0

flutter:
  uses-material-design: true
